epochs:
  desc: "Number of epochs to train over"
  value: 20
folds:
  desc: "the number of Kfolds"
  value: 5
labels:
  desc: "The number of unique topics"
  value: 15
verbose_steps:
  desc:
  value: 500
early_stopping:
  desc: "early stopping callback x epochs after best result recorded"
  value: True
patience:
  desc: "the number of epochs after best recorded score before early stopping callback"
  value: 5
batch_size:
  desc: "Size of each mini-batch"
  value: 8
Dataset:
  desc: "kaggle feedback prize competition dataset"
  value:
Framework:
  desc: "Pytorch"
  value:
Architecture:
  desc: "hugging face transformer architecture"
  value: "transformer"
Model:
  desc: "longerformer model from AllenAi"
  value: "longformer-base-4096"
Optimizer:
  desc: "AdamW"
  value:
Metric:
  desc: "f1"
  value:

